// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsewuplyllwliohecyhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzZXd1cGx5bGx3bGlvaGVjeWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4OTQ3MDIsImV4cCI6MjA1MTQ3MDcwMn0.hz_xq5EOrrV6ZQDgHmOuDXmCyO1mhssMYlGCvj7t8nc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);